### ISSUE TITLE
npm test fail

### ISSUE THREAD

**Issue by zlemon819** [Electron-Labs/ed25519-circom#137]
hi, i try to execute 'npm run test-scalarmul', but come across the following error. Can anyone help it ? Thank you.
------------------------------------------------------------------------------------------------------------------------------------------
> @electron-labs/ed25519-circom@0.0.1 test-scalarmul
> mocha --colors --max-old-space-size=4000 --timeout 300000 test/scalarmul.test.js

  Scalar multiplication for ed25519
    when performing scalar multiplication on curve 
      1) should multiply them correctly

  0 passing (1m)
  1 failing

  1) Scalar multiplication for ed25519
       when performing scalar multiplication on curve 
         should multiply them correctly:
     LinkError: WebAssembly.instantiate(): Import #1 module="runtime" function="printErrorMessage" error: function import requires a callable
      at builder (node_modules/circom_tester/wasm/witness_calculator.js:19:40)
      at async wasm_tester (node_modules/circom_tester/wasm/tester.js:60:16)
      at async Context.<anonymous> (test/scalarmul.test.js:9:19)

**Comment by jinankjain** [comment]
I just ran the test on the master branch and it does not seems to fail:

```
❯ npm run test-scalarmul

> ed25519-circom@0.0.1 test-scalarmul
> mocha --colors --max-old-space-size=4000 --timeout 300000 test/scalarmul.test.js



  Scalar multiplication for ed25519
    when performing scalar multiplication on curve
      ✔ should multiply them correctly (108142ms)


  1 passing (2m)
```

**Comment by zlemon819** [comment]
> I just ran the test on the master branch and it does not seems to fail:
> 
> ```
> ❯ npm run test-scalarmul
> 
> > ed25519-circom@0.0.1 test-scalarmul
> > mocha --colors --max-old-space-size=4000 --timeout 300000 test/scalarmul.test.js
> 
> 
> 
>   Scalar multiplication for ed25519
>     when performing scalar multiplication on curve
>       ✔ should multiply them correctly (108142ms)
> 
> 
>   1 passing (2m)
> ```
yes，i downgrade the circom version to 2.0.6 and now pass.

**Comment by jinankjain** [comment]
Closing this issue since we only support circom 2.0.6.
