### ISSUE TITLE
Hard to understand inputs meaning in verify.circom

### ISSUE THREAD

**Issue by Eikix** [Electron-Labs/ed25519-circom#62]
Hi all:),

First of: Really cool repo and thank you

I'm a beginner in zero-knowledge field, and i'm exploring different signature verification circuits in circom. 

Maybe this is a stupid question but i have a hard time fitting vars' names with their definition,
- msg = the message that was signed
- R8 and S = both parts of a edd25519 signature

but what are A, PointA and PointR ?

in my mind there was msg, signature, and pubKey so i'm guessing A, PointA and PointR have something to do with pubkeys.

**Proposed fix: adding one-lined comments above signal inputs in verify.circom to help readers map var names to actual definition of concepts**

**Comment by suniljalandhra** [comment]
Hey Eikix,

- ```A```  is a public key in the Integer form and you can get that from ```int.from_bytes(public, "little")```
- ```PointA``` and ```PointR``` are points on an elliptic curve which you get after point decompression of the public key(```A = point_decompress(public)```)  and signature (```R = point_decompress(Rs)```)  respectively.
- You can also refer to this [RFC](https://datatracker.ietf.org/doc/html/rfc8032#page-20) to understand more about ED25519

**Comment by rahulghangas** [comment]
@Eikix I have realized there needs to be better documentation regarding this.

One thing to note, it the circom way to pass in byte sequences not as little-endian/big-endian, but rather from lowest significant bit to most significant bit. We have assumed the same in these circuits.

To clarify on your doubts, A is the public key in binary (LSB to MSB)
`PointA` is the point representing the public on the elliptic curve (encoded in base 2^51 for brevity)
`PointR` is the point representing the R8 value on the elliptic curve (encoded in base 2^51)

Ideally, the [algorithm](https://datatracker.ietf.org/doc/html/rfc8032#section-6) we follow only takes in `A` and `R8` in binary form, and is decompressed to get `PointA` and `PointR` respectively. However, decompression is an expensive algorithm to perform in a circuit. On the other hand, compression is cheap and easy to implement. So, we use a nifty little trick to push the onus of providing both to the `prover` and perform equality checks after compressing the points within the circuit. [Ref](https://github.com/Electron-Labs/ed25519-circom/blob/532f638b4d6ae4684a1f0907df6c92676f0ae8df/circuits/verify.circom#L57)

You can find all helper functions to change encodings from well-known formats to circuit friendly formats [here](https://github.com/Electron-Labs/ed25519-circom/blob/master/test/utils.js)

I will add comments in the circuit files to address your proposed solution, post which we can close this issue

**Comment by Eikix** [comment]
Thank you for your help:) That was very clear

**Comment by rahulghangas** [comment]
Fixed in commit ba4c2dfdb8f5ff3a24de84c1f7cef610ab417b8e
